#!/usr/bin/env bash
# One-time setup: install deps + add agent-kit to PATH.
# Idempotent: safe to re-run.

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "Bootstrap from $DIR"

# 1. Verify Node (the only runtime dep; we drove out the APM CLI in v0.6+)
if ! command -v node >/dev/null 2>&1; then
  echo "Error: Node 20+ is required. Install from https://nodejs.org" >&2
  exit 1
fi

# 2. Install Node deps
echo "[1/2] npm install"
( cd "$DIR" && npm install --no-audit --no-fund --silent )

# 3. PATH setup — write a shim at ~/.local/bin that exec's the real launcher.
#    Avoids the Windows symlink-permission trap: `ln -s` on MSYS/Git Bash
#    without admin/developer-mode falls back to `cp`, which produces a
#    detached copy of bin/agent-kit. The copy's BASH_SOURCE-based path
#    resolution then mistakes `~/.local/bin` for the install root and can't
#    find lib/wizard.js. A shim that hard-codes the source path sidesteps
#    that entirely and works identically on Linux/macOS/Windows.
LINK_TARGET="$HOME/.local/bin/agent-kit"
SOURCE_BIN="$DIR/bin/agent-kit"

mkdir -p "$HOME/.local/bin"
chmod +x "$SOURCE_BIN"

if [ -L "$LINK_TARGET" ] || [ -f "$LINK_TARGET" ]; then
  rm -f "$LINK_TARGET"
fi
cat > "$LINK_TARGET" <<EOF
#!/usr/bin/env bash
# Auto-generated by my-agent-kits bootstrap.sh. Re-run bootstrap.sh to update.
exec "$SOURCE_BIN" "\$@"
EOF
chmod +x "$LINK_TARGET"
echo "[2/2] Wrote shim $LINK_TARGET -> $SOURCE_BIN"

# 4. PATH check
case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *)
    echo ""
    echo "Note: \$HOME/.local/bin is not on your PATH. Add this to ~/.bashrc:"
    echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
    ;;
esac

echo ""
echo "Done. Try: agent-kit help"
