// lib/apm-writer.js
// Generate the per-repo apm.yml that lists my-agent-kits as a dep and sets targets.
// Pure: takes config object, returns YAML string.

import { stringify as yamlStringify } from "yaml";
import { resolveAgent } from "./agents.js";

export function generateApmYml({ repoName, agents, kitRef = "superliaye/my-agent-kits" }) {
  const targets = agents.map((a) => resolveAgent(a).apmTarget);

  // The leading comment is a marker the wizard reads to detect kit-managed
  // apm.yml on subsequent runs (vs user-authored).
  const header = "# Generated by agent-kit. Edits will be overwritten on next init/update.\n";
  return header + yamlStringify({
    name: repoName,
    version: "1.0.0",
    description: `Agent kit configuration for ${repoName}`,
    dependencies: {
      apm: [kitRef],
      mcp: [],
    },
    targets,
  });
}
