// lib/deploy.js
// Orchestrates the actual deployment: write apm.yml, run apm install, run apm compile,
// perform post-steps (Codex global copy, AGENTS.override.md), and write .agent-kit.yaml.

import { writeFileSync, mkdirSync, copyFileSync, appendFileSync, readFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { spawnSync } from "node:child_process";
import { homedir } from "node:os";
import { resolveAgent } from "./agents.js";
import { generateApmYml } from "./apm-writer.js";
import { writeState, readKitVersion } from "./state.js";
import { listAllPrimitives, parseFrontmatter } from "./primitives.js";
import { realpathSync } from "node:fs";

const APM_HOME = join(homedir(), ".apm");

export function deploy({ repoDir, kitRoot, preset, agents, scope, primitives, codexPersonalLayer = false, isUpdate = false, kitRef }) {
  const log = (line) => process.stdout.write(line + "\n");
  // Resolve kit reference for apm.yml. Order: explicit arg > env var > default GitHub shorthand.
  if (!kitRef) kitRef = process.env.AGENT_KIT_REF || "superliaye/my-agent-kits";

  // 1. Write apm.yml at the deploy target dir
  const apmCwd = scope === "global" ? APM_HOME : repoDir;
  const apmYmlPath = join(apmCwd, "apm.yml");
  const repoName = scope === "global" ? "user-global" : (basename(repoDir) || "repo");
  ensureDir(apmCwd);

  // If apm.yml exists and isn't agent-kit-managed, warn the user we're about
  // to clobber it. Detection: agent-kit-generated apm.yml carries the kit ref
  // in its dependencies.apm list. Anything else is hand-authored.
  if (existsSync(apmYmlPath)) {
    const existing = readFileSync(apmYmlPath, "utf8");
    if (!existing.includes(kitRef) && !existing.includes("Generated by agent-kit")) {
      log(`! Existing apm.yml at ${apmYmlPath} will be overwritten`);
      log(`  (it does not reference ${kitRef}; back it up if it has hand-authored content)`);
    }
  }

  writeFileSync(apmYmlPath, generateApmYml({ repoName, agents, kitRef }));
  log(`✓ Wrote ${apmYmlPath}`);

  // 2. Run apm install with explicit --target so the user-scope/global deploy
  //    doesn't depend on APM's auto-detect (which is environment-sensitive —
  //    e.g. inside a clean Linux container only `copilot` is auto-detected).
  const targets = agents.map((a) => resolveAgent(a).apmTarget).join(",");
  const installArgs = ["install", "--force", "--target", targets];
  if (scope === "global") installArgs.push("-g");
  if (isUpdate) installArgs.push("--update");
  runApm(installArgs, apmCwd, log);

  // 3. Run apm compile -t claude,codex (compile drives Codex AGENTS.md and is
  //    a no-op for Claude beyond what install already wrote).
  runApm(["compile", "-t", targets], apmCwd, log);

  // 4. Codex global copy step
  if (scope === "global" && agents.includes("codex")) {
    const src = join(APM_HOME, "AGENTS.md");
    const dst = join(homedir(), ".codex", "AGENTS.md");
    if (!existsSync(src)) {
      throw new Error(`Codex global copy: source missing at ${src} (apm compile may have failed)`);
    }
    ensureDir(dirname(dst));
    copyFileSync(src, dst);
    log(`✓ Codex global: copied ${src} → ${dst}`);
  }

  // 5. Codex personal layer (repo scope only, opt-in)
  if (scope === "repo" && agents.includes("codex") && codexPersonalLayer) {
    const overridePath = join(repoDir, "AGENTS.override.md");
    const concat = concatInstructionsForOverride(kitRoot, primitives.instructions ?? []);
    writeFileSync(overridePath, concat);
    log(`✓ Wrote ${overridePath} (personal layer)`);
    appendToGitignore(repoDir, "AGENTS.override.md");
    log(`✓ Added AGENTS.override.md to .gitignore`);
  }

  // 5b. Claude Code plugins (always at user scope in v0.2; documented).
  //     Plugins selected in the wizard get installed via `claude plugin install`.
  //     The marketplace is added first (idempotent) so the install can resolve it.
  //     For Codex/other agents, plugins are a no-op (this primitive is Claude-only).
  let installedPlugins = [];
  if (agents.includes("claude") && (primitives.plugins ?? []).length > 0) {
    installedPlugins = deployPlugins(kitRoot, primitives.plugins, log);
  }

  // 5c. v0.3: Codex sidecar generation for skills. Skills are authored in
  //     Claude format (SKILL.md with `disable-model-invocation: true`). For
  //     Codex coverage, the wizard emits `agents/openai.yaml` alongside each
  //     deployed SKILL.md with the equivalent Codex policy. Author writes
  //     once; this step translates per-vendor at deploy time.
  if (agents.includes("codex") && (primitives.skills ?? []).length > 0) {
    compileSkillsForCodex(repoDir, scope, primitives, log);
  }

  // 6. Write/refresh .agent-kit.yaml in repoDir.
  //    Persist plugins ONLY for the actually-Claude case AND only the ones that
  //    successfully installed — so a future `agent-kit update` doesn't think a
  //    failed install was a success, and a Codex-only repo doesn't carry stale
  //    plugin entries that would surprise on a later flip to Claude.
  if (scope === "repo") {
    const persistedPrimitives = { ...primitives };
    if (!agents.includes("claude")) {
      persistedPrimitives.plugins = [];
    } else if ((primitives.plugins ?? []).length > 0) {
      persistedPrimitives.plugins = installedPlugins;
    }
    writeState(repoDir, {
      preset: preset.name,
      kitVersion: readKitVersion(kitRoot),
      agents,
      scope,
      codexPersonalLayer,
      primitives: persistedPrimitives,
    });
    log(`✓ Wrote ${repoDir}/.agent-kit.yaml`);
  }
}

function runApm(args, cwd, log) {
  log(`> apm ${args.join(" ")}  (cwd: ${cwd})`);
  const r = spawnSync("apm", args, { cwd, stdio: "inherit", shell: process.platform === "win32" });
  if (r.status !== 0) {
    throw new Error(`apm ${args.join(" ")} exited ${r.status}`);
  }
}

function ensureDir(p) {
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

function basename(p) {
  return p.replace(/[\\/]+$/, "").split(/[\\/]/).pop() || "";
}

function concatInstructionsForOverride(kitRoot, instructionNames) {
  const parts = ["# AGENTS.override.md", "<!-- Personal layer, gitignored. Generated by agent-kit. -->", ""];
  for (const name of instructionNames) {
    const p = join(kitRoot, ".apm", "instructions", `${name}.instructions.md`);
    if (!existsSync(p)) continue;
    parts.push(stripFrontmatter(readFileSync(p, "utf8")));
    parts.push("");
  }
  return parts.join("\n");
}

function stripFrontmatter(s) {
  if (!s.startsWith("---")) return s;
  const end = s.indexOf("\n---", 3);
  if (end < 0) return s;
  return s.slice(end + 4).replace(/^\n+/, "");
}

function appendToGitignore(repoDir, line) {
  const gi = join(repoDir, ".gitignore");
  let cur = "";
  if (existsSync(gi)) cur = readFileSync(gi, "utf8");
  if (cur.split(/\r?\n/).includes(line)) return;
  if (cur.length && !cur.endsWith("\n")) cur += "\n";
  writeFileSync(gi, cur + line + "\n");
}

// Whitelist for plugin frontmatter values used in shell calls. Rejects shell
// metacharacters even though spawnSync without shell:true escapes them — on
// Windows we use shell:true to pick up apm.cmd / claude.cmd shims, and an
// unsanitized value from a poisoned plugin file would inject. Only allow
// alnum + a small set of harmless punctuation needed for marketplace specs.
const SAFE_REF_PATTERN = /^[A-Za-z0-9._/@\-:+#]+$/;

// v0.3: For each deployed skill that has `disable-model-invocation: true` in
// its SKILL.md frontmatter, generate a Codex-side `agents/openai.yaml` sidecar
// with the equivalent `policy.allow_implicit_invocation: false`. APM ships
// SKILL.md to the cross-client `.agents/skills/<name>/` location for Codex
// target — this step adds the Codex-specific sidecar there.
//
// Uses primitives.js's real-yaml parseFrontmatter — handles lists, comments,
// YAML truthy variants, multi-line values, etc. Previously hand-rolled and
// caught by code review as fragile.
function compileSkillsForCodex(repoDir, scope, primitives, log) {
  // APM's per-repo skills deploy lands at .agents/skills/<name>/SKILL.md.
  if (scope !== "repo") {
    if ((primitives.skills ?? []).length > 0) {
      log(`! WARNING: Codex global skill sidecar generation is NOT supported in v0.3.`);
      log(`!   Manual-only invocation policy will NOT be enforced for Codex at global scope.`);
      log(`!   Workaround: run \`agent-kit init --scope repo --agents codex\` per-repo.`);
    }
    return;
  }
  const skillsRoot = join(repoDir, ".agents", "skills");
  if (!existsSync(skillsRoot)) {
    log(`! Codex sidecar: no .agents/skills/ found at ${skillsRoot} (apm may have skipped skill deploy)`);
    return;
  }
  // Resolve the real path of the skills root so we can defensively check that
  // any per-skill folder doesn't symlink out of containment. The kit content
  // is trusted today, but symlinked dirs inside an upstream APM package would
  // bypass our path joining without this check.
  let realSkillsRoot;
  try { realSkillsRoot = realpathSync(skillsRoot); } catch { return; }

  let count = 0;
  for (const entry of readDirSafely(skillsRoot)) {
    const skillDir = join(skillsRoot, entry);
    const skillMd = join(skillDir, "SKILL.md");
    if (!existsSync(skillMd)) continue;
    // Containment check: realpath of skillDir must be under realpath of skillsRoot.
    let realSkillDir;
    try { realSkillDir = realpathSync(skillDir); } catch { continue; }
    if (!realSkillDir.startsWith(realSkillsRoot)) {
      log(`! Skipping skill '${entry}': resolves outside .agents/skills/ (symlink?)`);
      continue;
    }
    const fm = parseFrontmatter(readFileSync(skillMd, "utf8"));
    if (fm["disable-model-invocation"] !== true) continue;
    const sidecarDir = join(skillDir, "agents");
    ensureDir(sidecarDir);
    const sidecarPath = join(sidecarDir, "openai.yaml");
    writeFileSync(sidecarPath, "policy:\n  allow_implicit_invocation: false\n");
    log(`✓ Codex sidecar: wrote ${sidecarPath} (manual-only)`);
    count++;
  }
  log(`✓ Compiled ${count} skill(s) for Codex (manual-only policy)`);
}

function readDirSafely(p) {
  try { return readdirSync(p); } catch { return []; }
}

function deployPlugins(kitRoot, pluginNames, log) {
  if (!pluginNames || pluginNames.length === 0) return [];
  const all = listAllPrimitives();
  const installed = [];
  const claudeAvailable = spawnSync("claude", ["--version"], { stdio: "pipe", shell: process.platform === "win32" }).status === 0;
  if (!claudeAvailable) {
    log(`! Claude Code CLI not on PATH. Skipping plugin installs (${pluginNames.length}). Install Claude Code, then re-run \`agent-kit init\` or run \`claude plugin install\` manually.`);
    return installed;
  }
  for (const name of pluginNames) {
    const meta = (all.plugins ?? []).find((p) => p.name === name);
    if (!meta) {
      log(`! Plugin '${name}' not found in kit. Skipping.`);
      continue;
    }
    const source = meta.marketplaceSource;
    const market = meta.marketplaceName;
    const pname  = meta.pluginName || name;
    if (!source || !market) {
      log(`! Plugin '${name}' missing marketplace_source/marketplace_name in frontmatter. Skipping.`);
      continue;
    }
    if (!SAFE_REF_PATTERN.test(source) || !SAFE_REF_PATTERN.test(market) || !SAFE_REF_PATTERN.test(pname)) {
      log(`! Plugin '${name}' has unsafe characters in marketplace_source/marketplace_name/plugin_name. Skipping (potential injection).`);
      continue;
    }
    log(`> claude plugin marketplace add ${source}`);
    const m = spawnSync("claude", ["plugin", "marketplace", "add", source], { stdio: "inherit", shell: process.platform === "win32" });
    if (m.status !== 0) {
      log(`! claude plugin marketplace add ${source} exited ${m.status}; skipping plugin install for ${pname}`);
      continue;
    }
    log(`> claude plugin install ${pname}@${market} --scope user`);
    const r = spawnSync("claude", ["plugin", "install", `${pname}@${market}`, "--scope", "user"], { stdio: "inherit", shell: process.platform === "win32" });
    if (r.status !== 0) {
      log(`! claude plugin install ${pname}@${market} exited ${r.status}; not recording in state so update can retry`);
      continue;
    }
    log(`✓ Installed plugin ${pname}@${market} (user scope; auto-update via Claude Code at startup)`);
    installed.push(name);
  }
  return installed;
}
