// lib/deploy.js
// Orchestrates the actual deployment: write apm.yml, run apm install, run apm compile,
// perform post-steps (Codex global copy, AGENTS.override.md), and write .agent-kit.yaml.

import { writeFileSync, mkdirSync, copyFileSync, appendFileSync, readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { spawnSync } from "node:child_process";
import { homedir } from "node:os";
import { resolveAgent } from "./agents.js";
import { generateApmYml } from "./apm-writer.js";
import { writeState, readKitVersion } from "./state.js";

const APM_HOME = join(homedir(), ".apm");

export function deploy({ repoDir, kitRoot, preset, agents, scope, primitives, codexPersonalLayer = false, isUpdate = false, kitRef = "superliaye/my-agent-kits" }) {
  const log = (line) => process.stdout.write(line + "\n");

  // 1. Write apm.yml at the deploy target dir
  const apmCwd = scope === "global" ? APM_HOME : repoDir;
  const apmYmlPath = join(apmCwd, "apm.yml");
  const repoName = scope === "global" ? "user-global" : (basename(repoDir) || "repo");
  ensureDir(apmCwd);
  writeFileSync(apmYmlPath, generateApmYml({ repoName, agents, kitRef }));
  log(`✓ Wrote ${apmYmlPath}`);

  // 2. Run apm install
  const installArgs = ["install", "--force"];
  if (scope === "global") installArgs.push("-g");
  if (isUpdate) installArgs.push("--update");
  runApm(installArgs, apmCwd, log);

  // 3. Run apm compile -t claude,codex
  const targets = agents.map((a) => resolveAgent(a).apmTarget).join(",");
  runApm(["compile", "-t", targets], apmCwd, log);

  // 4. Codex global copy step
  if (scope === "global" && agents.includes("codex")) {
    const src = join(APM_HOME, "AGENTS.md");
    const dst = join(homedir(), ".codex", "AGENTS.md");
    if (!existsSync(src)) {
      throw new Error(`Codex global copy: source missing at ${src} (apm compile may have failed)`);
    }
    ensureDir(dirname(dst));
    copyFileSync(src, dst);
    log(`✓ Codex global: copied ${src} → ${dst}`);
  }

  // 5. Codex personal layer (repo scope only, opt-in)
  if (scope === "repo" && agents.includes("codex") && codexPersonalLayer) {
    const overridePath = join(repoDir, "AGENTS.override.md");
    const concat = concatInstructionsForOverride(kitRoot, primitives.instructions ?? []);
    writeFileSync(overridePath, concat);
    log(`✓ Wrote ${overridePath} (personal layer)`);
    appendToGitignore(repoDir, "AGENTS.override.md");
    log(`✓ Added AGENTS.override.md to .gitignore`);
  }

  // 6. Write/refresh .agent-kit.yaml in repoDir
  if (scope === "repo") {
    writeState(repoDir, {
      preset: preset.name,
      kitVersion: readKitVersion(kitRoot),
      agents,
      scope,
      codexPersonalLayer,
      primitives,
    });
    log(`✓ Wrote ${repoDir}/.agent-kit.yaml`);
  }
}

function runApm(args, cwd, log) {
  log(`> apm ${args.join(" ")}  (cwd: ${cwd})`);
  const r = spawnSync("apm", args, { cwd, stdio: "inherit", shell: process.platform === "win32" });
  if (r.status !== 0) {
    throw new Error(`apm ${args.join(" ")} exited ${r.status}`);
  }
}

function ensureDir(p) {
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

function basename(p) {
  return p.replace(/[\\/]+$/, "").split(/[\\/]/).pop() || "";
}

function concatInstructionsForOverride(kitRoot, instructionNames) {
  const parts = ["# AGENTS.override.md", "<!-- Personal layer, gitignored. Generated by agent-kit. -->", ""];
  for (const name of instructionNames) {
    const p = join(kitRoot, "primitives", "instructions", `${name}.instructions.md`);
    if (!existsSync(p)) continue;
    parts.push(stripFrontmatter(readFileSync(p, "utf8")));
    parts.push("");
  }
  return parts.join("\n");
}

function stripFrontmatter(s) {
  if (!s.startsWith("---")) return s;
  const end = s.indexOf("\n---", 3);
  if (end < 0) return s;
  return s.slice(end + 4).replace(/^\n+/, "");
}

function appendToGitignore(repoDir, line) {
  const gi = join(repoDir, ".gitignore");
  let cur = "";
  if (existsSync(gi)) cur = readFileSync(gi, "utf8");
  if (cur.split(/\r?\n/).includes(line)) return;
  if (cur.length && !cur.endsWith("\n")) cur += "\n";
  writeFileSync(gi, cur + line + "\n");
}
