#!/usr/bin/env bash
# v0.5: when CLAUDE.md pre-exists in a repo, `agent-kit init --claude-md concat`
# should preserve the user's content and append agent-kit's lean output between
# idempotent markers. Re-running init must detect the marker and replace the
# block in place (not double-append).
set -u
HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$HERE/../lib/assertions.sh"

WORK="$(mktemp -d)"
trap "rm -rf '$WORK'" EXIT
cd "$WORK"
git init -q .

# Pre-create a user CLAUDE.md with hand-authored content
cat > "$WORK/CLAUDE.md" <<'EOF'
# My Project

This is hand-authored content that I care about.

## My section

Some rules I wrote myself.
EOF

"$KIT_ROOT/bin/agent-kit" init --preset engineering --agents claude --scope repo --claude-md concat \
  || { fail "agent-kit init exited non-zero"; exit 1; }

# User content preserved
assert_content_contains "$WORK/CLAUDE.md" "This is hand-authored content that I care about." "user content preserved"
assert_content_contains "$WORK/CLAUDE.md" "Some rules I wrote myself." "user section preserved"

# Agent-kit markers present
assert_content_contains "$WORK/CLAUDE.md" "agent-kit:claude-md:start" "start marker present"
assert_content_contains "$WORK/CLAUDE.md" "agent-kit:claude-md:end" "end marker present"

# Agent-kit content present
assert_content_contains "$WORK/CLAUDE.md" "Delete commented-out code and personal dev notes" "core instruction merged in"
assert_content_contains "$WORK/CLAUDE.md" "Think Before Coding" "karpathy instruction merged in"

# APM boilerplate stripped (lean output)
if grep -q "Build ID:" "$WORK/CLAUDE.md"; then fail "APM Build ID not stripped"; else ok "APM Build ID stripped"; fi
if grep -q "APM Version:" "$WORK/CLAUDE.md"; then fail "APM Version not stripped"; else ok "APM Version stripped"; fi
if grep -q "Source: local" "$WORK/CLAUDE.md"; then fail "Source markers not stripped"; else ok "Source markers stripped"; fi
if grep -q "This file was generated by APM CLI. Do not edit manually." "$WORK/CLAUDE.md"; then
  fail "APM footer not stripped"
else
  ok "APM footer stripped"
fi
# Inside the agent-kit section: redundant `# Dependencies` block + `@apm_modules/...` @-ref stripped
if grep -A1 "agent-kit:claude-md:start" "$WORK/CLAUDE.md" | grep -q "^# Dependencies"; then
  fail "# Dependencies block not stripped"
else
  ok "# Dependencies block stripped"
fi
if grep -q "@apm_modules/superliaye/my-agent-kits/CLAUDE.md" "$WORK/CLAUDE.md"; then
  fail "@apm_modules @-ref not stripped"
else
  ok "@apm_modules @-ref stripped"
fi
# Wrapper headings stripped — rule bodies should be concatenated cleanly
if grep -q "^# Project Standards" "$WORK/CLAUDE.md"; then
  fail "# Project Standards wrapper not stripped"
else
  ok "# Project Standards wrapper stripped"
fi
if grep -q "^## Files matching" "$WORK/CLAUDE.md"; then
  fail "## Files matching glob subheadings not stripped"
else
  ok "## Files matching glob subheadings stripped"
fi
# Rule bodies themselves are present (their own H1 headings serve as section markers)
assert_content_contains "$WORK/CLAUDE.md" "# Core Instructions" "Core Instructions section present"
assert_content_contains "$WORK/CLAUDE.md" "# TypeScript Rules" "TypeScript Rules section present"

# State recorded the merge choice for future updates
assert_content_contains "$WORK/.agent-kit.yaml" "claude_md_merge: concat" "merge strategy recorded in state"

# Idempotency: re-run with same flags must replace marker block in place, not double-append.
SIZE_BEFORE=$(stat -c%s "$WORK/CLAUDE.md" 2>/dev/null || stat -f%z "$WORK/CLAUDE.md")
"$KIT_ROOT/bin/agent-kit" init --preset engineering --agents claude --scope repo --claude-md concat \
  || { fail "second init exited non-zero"; exit 1; }
SIZE_AFTER=$(stat -c%s "$WORK/CLAUDE.md" 2>/dev/null || stat -f%z "$WORK/CLAUDE.md")
if [ "$SIZE_BEFORE" = "$SIZE_AFTER" ]; then
  ok "idempotent on re-run: file size unchanged ($SIZE_BEFORE bytes)"
else
  fail "not idempotent: size $SIZE_BEFORE -> $SIZE_AFTER"
fi

# Exactly one pair of markers (not double-appended)
START_COUNT=$(grep -c "agent-kit:claude-md:start" "$WORK/CLAUDE.md" || true)
END_COUNT=$(grep -c "agent-kit:claude-md:end" "$WORK/CLAUDE.md" || true)
if [ "$START_COUNT" = "1" ] && [ "$END_COUNT" = "1" ]; then
  ok "exactly one pair of markers after re-run"
else
  fail "expected 1 start + 1 end marker, got $START_COUNT start + $END_COUNT end"
fi
