#!/usr/bin/env bash
set -u
HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$HERE/../lib/assertions.sh"

WORK="$(mktemp -d)"
trap "rm -rf '$WORK'" EXIT
cd "$WORK"
git init -q .

agent-kit init --preset personal --agents codex --scope repo --yes \
  || { fail "agent-kit init exited non-zero"; exit 1; }

assert_file_exists "$WORK/AGENTS.md"     "AGENTS.md"
assert_content_contains "$WORK/AGENTS.md" "Generated by APM"  "build-id marker"
assert_size_under "$WORK/AGENTS.md" 32768 "AGENTS.md size <= 32 KiB"
assert_file_exists "$WORK/.agent-kit.yaml" "state file"
