#!/usr/bin/env bash
set -u
HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$HERE/../lib/assertions.sh"

WORK="$(mktemp -d)"
trap "rm -rf '$WORK'" EXIT
cd "$WORK"
git init -q .

agent-kit init --preset engineering --agents codex --scope repo --yes \
  || { fail "agent-kit init exited non-zero"; exit 1; }

assert_file_exists "$WORK/AGENTS.md"     "AGENTS.md"
assert_content_contains "$WORK/AGENTS.md" "Generated by APM"  "build-id marker"
assert_size_under "$WORK/AGENTS.md" 32768 "AGENTS.md size <= 32 KiB"
assert_file_exists "$WORK/.agent-kit.yaml" "state file"
# v0.3: skills deploy to .agents/skills/<name>/ (cross-client convention).
# engineering preset ships 9 skills.
assert_dir_nonempty "$WORK/.agents/skills" "cross-client skills root"
assert_file_exists "$WORK/.agents/skills/my-commit/SKILL.md" "my-commit skill deployed"
# v0.3: wizard generates Codex sidecar with allow_implicit_invocation: false
# because all our skills have disable-model-invocation: true in SKILL.md.
assert_file_exists "$WORK/.agents/skills/my-commit/agents/openai.yaml" "Codex sidecar generated"
assert_content_contains "$WORK/.agents/skills/my-commit/agents/openai.yaml" "allow_implicit_invocation: false" "sidecar policy correct"
