#!/usr/bin/env bash
set -u
HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$HERE/../lib/assertions.sh"

WORK="$(mktemp -d)"
trap "rm -rf '$WORK'" EXIT
cd "$WORK"
git init -q .

agent-kit init --preset engineering --agents codex --scope global --yes \
  || { fail "agent-kit init --scope global exited non-zero"; exit 1; }

assert_file_exists "$HOME/.codex/AGENTS.md"  "global AGENTS.md"
assert_content_contains "$HOME/.codex/AGENTS.md" "Generated by APM"  "build-id marker"
assert_files_equal "$HOME/.apm/AGENTS.md" "$HOME/.codex/AGENTS.md" "global codex copy fidelity"
